### ISSUE TITLE
Branch structure is confusing

### ISSUE THREAD

**Issue by paride** [canonical/probert#94]
I don't fully get the current branch structure, or the packaging workflow behind it.

It seems that the packaging (changes to `debian/*` including "release" changes to `d/changelog`) has been done in master so far, but also in the `ubuntu/devel` branch, which is currently ahead of master in terms of packaging (has commits to `debian/` that master doesn't have). It looks like there was a partial transition to a packaging branch (`ubuntu/devel`), but this was not completed by a `rm -rf debian` in master.

Given that probert is a native package I propose to follow https://dep-team.pages.debian.net/deps/dep14/, section Native packages, and have:

- The `master` branch for development *and* packaging for the current Ubuntu development release
- Release branches like `bionic` or `focal` for SRUs, branched off `master` as needed.

[DEP-14 is still in DRAFT state but is going to be finalized soon, there's an ongoing discussion in the debian-devel mailing list with some minor changes being proposed along with `s/DRAFT/ACCEPTED/`.]

Ping @xnox @blackboxsw @panlinux (from the MM conversation) and @raharper for the previous uploads.

**Comment by xnox** [comment]
> I don't fully get the current branch structure, or the packaging workflow behind it.
> 
> It seems that the packaging (changes to `debian/*` including "release" changes to `d/changelog`) has been done in master so far, but also in the `ubuntu/devel` branch, which is currently ahead of master in terms of packaging (has commits to `debian/` that master doesn't have). It looks like there was a partial transition to a packaging branch (`ubuntu/devel`), but this was not completed by a `rm -rf debian` in master.
> 
> Given that probert is a native package I propose to follow https://dep-team.pages.debian.net/deps/dep14/, section Native packages, and have:
> 
> * The `master` branch for development _and_ packaging for the current Ubuntu development release
> * Release branches like `bionic` or `focal` for SRUs, branched off `master` as needed.
> 
> [DEP-14 is still in DRAFT state but is going to be finalized soon, there's an ongoing discussion in the debian-devel mailing list with some minor changes being proposed along with `s/DRAFT/ACCEPTED/`.]
> 
> Ping @xnox @blackboxsw @panlinux (from the MM conversation) and @raharper for the previous uploads.

I think devel was used, when focal was frozen for release. We wanted to cherrypick targetted uploads, without taking more things from master that have been developed since.

I should make sense to make devel and master even when devel is open for any uploads, and close devel branch.

**Comment by paride** [comment]
@xnox then perhaps it should have been named `ubuntu/focal`...
